<?php

/**
 * Created by PhpStorm.
 * User: wangjin
 * Date: 2017/9/20
 * Time: 上午8:43
 * 商品分类
 */
class CategoryController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        $cid = intval(Help::getg('cid'));

        $assign = array(
            'pagetitle' => '分类',
            'active' => 'category',
        );
        // 一级分类
        $list = $this->db->select('sys_goods_category', ['id', 'name', 'orderby'], ['parentid' => 0, 'ORDER' => ['orderby']]);

        if ($cid > 0) {
            foreach ($list as $key => $val) {
                if ($list[$key]['id'] == $cid) {
                    $list[$key]['istop'] = 1;
                }
            }
            $childlist = $this->db->select('sys_goods_category', ['id', 'name', 'orderby', 'imgurl'], ['parentid' => $cid, 'ORDER' => ['orderby']]);
        } else {
            $list[0]['istop'] = 1;
            $childlist = $this->db->select('sys_goods_category', ['id', 'name', 'orderby', 'imgurl'], ['parentid' => $list[0]['id'], 'ORDER' => ['orderby']]);
        }
        $assign['list'] = $list;
        $assign['childlist'] = $childlist;
        // render
        echo $this->twig->render('/category/index.html', $assign);
    }
}